# Stage 1 - the build process
FROM node:11.14.0 as deps
ARG firebaseEnvironment
ARG ssh_prv_key
RUN mkdir -p /root/.ssh
RUN echo "$ssh_prv_key" > /root/.ssh/id_rsa && \
   chmod 600 /root/.ssh/id_rsa
RUN ssh -o StrictHostKeyChecking=no -vT git@code.knolskape.com 2>&1 | grep -i aut

# WORKDIR  /src/app

COPY package.json yarn.lock ./
RUN yarn

COPY . ./
RUN yarn build

#install firebease cli 
RUN npm config set unsafe-perm true \
    && npm install -g firebase-tools
#export and deploy 
RUN export GOOGLE_APPLICATION_CREDENTIALS="$APP_HOME/gauth.json" && firebase deploy --only hosting:"$firebaseEnvironment" 



# FROM nginx

# COPY --from=deps ./build /usr/share/nginx/html


# EXPOSE 80 443
